version: 2.1
orbs:
  android: circleci/android@2.1.2

jobs:
  build-native-library:
    docker:
      - image: cimg/android:2023.02.1-ndk
    steps:
      - checkout
      - run: ls
      - run: chmod +x .android/circlecinative_build.sh
      - run: .android/circlecinative_build.sh
      - store_artifacts:
          path: circlenative-build-artifacts.tar.gz
workflows:
  build-native-library-wf:
    jobs:
      - build-native-library:
          name: build-native-library