version: 2.1
orbs:
  android: circleci/android@2.1.2

jobs:
  build-native-library:
    docker:
      - image: cimg/android:2023.02.1-ndk
    steps:
      - checkout
      - run: cd .android; pwd;
      - run: ls
      - run: chmod +x circlecinative_build.sh
      - run: ./circlecinative_build.sh
      - store_artifacts:
          path: .circleci/arm64-v8a/libcirclecinative.so
      - store_artifacts:
          path: .circleci/armeabi-v7a/libcirclecinative.so
workflows:
  build-native-library-wf:
    jobs:
      - build-native-library:
          name: build-native-library